### ISSUE TITLE
About Sync v0.0.52 has stopped working (Firefox Version 78.0.1)

### ISSUE THREAD

**Issue by rthx** [mozilla-extensions/aboutsync#75]
About Sync v0.0.51 works
after update to 0.0.52, about:sync is no longer displayed under about:about
Calling about:sync directly fails, brings an error message
Firefox version 78.0.1 (Windows)
Downgrade to v0.0.51 and it works again.
I had the same thing with earlier versions of Firefox, but no longer know which 7x version.

**Comment by mhammond** [comment]
That's very odd - it worked fine for me when 78 was Nightly. What error message do you get?

**Comment by rthx** [comment]
Just checked my notes, Firefox_74.0.1 (32-bit) didn't work after upgrading from v0.0.51 to v0.0.52.
But I didn't think anything of it, because after the downgrade to v0.0.51 it worked again.
But now I'm one step further, looks like it has to do with my profile, because with another profile (same PC, same Firefox) it also works after upgrading to v0.0.52
Do you have a tip on what it could be or how I could narrow it down - or what has changed between v0.0.51 and v0.0.52.

**Comment by mhammond** [comment]
I can't think of anything that changed which sounds like that. Can you give me any clues at all as to what you are seeing. The first comment mentioned an error message without saying what it is. Maybe a screenshot? It's almost certain that the console, or possibly even the sync logs have some evidence.

**Comment by dannycolin** [comment]
Today, I got the same issue but I resolved it by downgrading and updating again.

**Comment by mhammond** [comment]
How odd - my firefox 82 nightly shows I'm running 0.0.52 which last updated in march, and it continues to work fine.

**Comment by egrieco** [comment]
Something is up. I'm getting an "Invalid URL" error when I try to go to `about:sync`:

> Hmm. That address doesn’t look right.
> 
> Please check that the URL is correct and try again.

"About Sync" is not showing up in the tools menu either.

I'm running **Firefox 101.0b5**. Though this has been happening for a while. Hadn't had the time to troubleshoot until now.

Also, the about text in the Add-ons Manager lists the old GitHub url.

**Comment by mhammond** [comment]
thanks - we had a few bumps releasing a new version, but they are now resolved and there should be a new release out in the next day or so.

**Comment by egrieco** [comment]
I'll keep an eye out for it and let you know if I'm still seeing any issues.

**Comment by mhammond** [comment]
New version is on AMO 🎉

**Comment by mhammond** [comment]
(I'm actually going to close this now - I still haven't got to the bottom of the OP's original problem, but a new issue for problems with the new release probably makes sense.

**Comment by egrieco** [comment]
Yay, it's working again!

Thank you. This is still the easiest way for me to pull open tabs on my mobile out of FXA. I'll probably write something in rust that can do it from the CLI eventually, but until then...
